name: rad_pipeline_env
channels:
  - conda-forge
dependencies:
  - ca-certificates>=2021.1.19
  - certifi>=2020.12.5
  - great-expectations
  - ipykernel>=5.1.4
  - matplotlib
  - jupyter
  - notebook
  - pandas>=1.0.3
  - pip>=20.0.2
  - prefect
  - python=3.8
  - python-graphviz
  - scipy>=1.4.1
  - setuptools>=47.1.1
  - xlrd=1.2.0
  - wheel>=0.34.2
  - pip:
    - datacompy
    - great_expectations
    - zipcodes
